### ISSUE TITLE
get_ofx -> 400 Bad Request error

### ISSUE THREAD

**Issue by castaway** [carpii/barclayscrape#5] opened 2024-05-14 13:27 UTC
heyho, the last few days my regular "get_ofx" call has started to create a file that just contains:
```
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```

instead of the OFX data, any ideas?

**Comment by carpii** [comment] 2024-05-15 17:57
Is there any error output from the app, or does it appear as if the ofx downloads successfully?

Does `get_ofx_combined` work, or have the same problem? I only use that feature personally, but it has been working

**Comment by castaway** [comment] 2024-05-17 09:51
Nope no errors, just downloads that content as the ofx file..

Today, get_ofx_combined says: `Error: data.ofx does not exist after attempting OFX download`
and get_ofx says `Warning: Could not retrieve account [20845883789160]. Possibly no transactions, or invalid accounttype.
` .. so now its more confusing..

**Comment by carpii** [comment] 2024-05-17 18:56
> Could not retrieve account

What type of account is this? 

The app attempts to filter out some account types which are unable to provide an OFX (such as mortgages, some investment accounts). Its possible I've missed one

Is this Bad Request affecting all OFX when using `get_ofx`, or just for a particular account?

Could you post the full console output when running `get_ofx` from cmdline?

**Comment by castaway** [comment] 2024-05-17 21:46
Same business/community account as ever, we only have one. Now its no longer producing the bad request, its doing Could not retrieve.. I guess barclays are changing things up again?

This is the entire thing:
`
/usr/src/extern/barclayscrape/barclayscrape.js --otp `/home/castaway/.local/bin/emvtool -r 0 -p XXXX cap` get_ofx .
Warning: Could not retrieve account [20845883789160]. Possibly no transactions, or invalid accounttype.
`

**Comment by carpii** [comment] 2024-05-17 21:58
You just have the one account with Barclays?

**Comment by castaway** [comment] 2024-05-18 15:07
Oh, this looks entirely different now:
![2024-05-18 16 06 56 bank barclays co uk 5252893824cd](https://github.com/carpii/barclayscrape/assets/109990/e7052f2b-3d33-45b8-a54e-930d89d19272)
![2024-05-18 16 06 46 bank barclays co uk 79d27ff5e28b](https://github.com/carpii/barclayscrape/assets/109990/5373356a-100e-4d53-8a5b-f32340072b96)

oops out of order .. there's now a "download & export" button which pops up a dialog box with some range / filetype choices
.. and I was slightly wrong earlier, the result of the get_ofx fetch is still a  400 bad request - would be handy if we didnt get a file at all when that happens..

**Comment by carpii** [comment] 2024-05-18 19:41
I can now reproduce the `get_ofx` problem

I'm working on a fix, although not sure what's involved yet

> get_ofx fetch is still a 400 bad request - would be handy if we didnt get a file at all when that happens..

I've added a fix for this - although there's no point pulling the latest github until `get_ofx` is fully fixed

**Comment by carpii** [comment] 2024-05-18 20:19
Could you try doing this manually, to see if it produces a suitable OFX for you?

Click the "Manage Accounts" header at the top

Click "Export My Transaction Data"

Now select an account for the 2nd drop down, and click Export

If this works I'll change `get_ofx` to use this feature, which will mean its almost identical to how `get_ofx_combined` works (less code to maintain)

**Comment by castaway** [comment] 2024-05-18 20:28
Yes that works

**Comment by castaway** [comment] 2024-05-19 09:54
> Today, get_ofx_combined says: `Error: data.ofx does not exist after attempting OFX download`

I just noticed why this is, I ended up with a data.csv instead

**Comment by carpii** [comment] 2024-05-19 16:16
Im not sure how thats possible. Are you saying if you delete the data.csv, and rerun `get_ofx_combined`, it recreates data.csv?

**Comment by castaway** [comment] 2024-05-19 17:15
That is correct, yup!

**Comment by carpii** [comment] 2024-05-19 17:28
But data.csv is actually OFX format (with the Bad Request in it)?

**Comment by castaway** [comment] 2024-05-19 17:29
Nope, contains CSV looking data.. header: `Number,Date,Account,Amount,Subcategory,Memo`

**Comment by carpii** [comment] 2024-05-19 17:34
Ok, that's very odd - I cant explain it

The CSV code hasnt been touched since I took over from the previous maintainer,. I'm surprised its even able pull any CSV data at all.  By coincidence, I stripped all the CSV code out of the project yesterday 

I've been able to reproduce the Bad Request problem with `get_ofx`, Im working on a fix for that and then we can see how its looking

**Comment by castaway** [comment] 2024-05-19 17:40
It's a weird and wonderful world..

**Comment by carpii** [comment] 2024-05-20 20:08
I thought this option always defaulted to MS Money, but I think its a default based on the last time you downloaded

![](https://i.imgur.com/VJNHnzZ.png)

Would explain why you are getting CSV, despite it using the OFX code. 

Is there a reason you want an individual OFX if you only have one account with Barclays?
Its adding some complexity since when you select a single account, it then demands a strict date range to be input (unlike `get_ofx_combined` which just pulls all available dates)

**Comment by castaway** [comment] 2024-05-21 09:17
No, its just what the examples suggested to do did when I installed it.. so that's what I used.. That is weird, and annoying! Make the dates parameters to the script? (assuming they can just be YYYY-MM-DD) - I can easily produce em

If combined can/does pull multiple files, named after the account (and can be forced to use ofx despite what was previously chosen), happy to use that too

**Comment by carpii** [comment] 2024-05-22 18:00
> Make the dates parameters to the script?

Unfortunately thats problematic too. Sometimes the latest date it can provide is yesterday, or in some cases even 2 days ago. If you try to just pass an end date beyond that, it refuses to download and the website shows an error (silly UX design). 

> If combined can/does pull multiple files, named after the account

`get_ofx_combined` downloads a single file containing all accounts (the OFX format supports this)

**Comment by carpii** [comment] 2024-05-22 20:34
Can you checkout the `get_ofx` git branch?

I think the `get_ofx` command should now be working again

- `get_ofx` no longer tries to parse transactions from account view, but uses similar export process to `get_ofx_combined`
- Selects the MS Money 2002 export format (instead of letting Barclays default to whatever you used last time)
- Parses the suggested date range, and passes that to download dialog
- Lots of changes to error handling

**Comment by castaway** [comment] 2024-05-22 20:39
That's looking pretty good! Aka I got an ofx file with useful looking contents

**Comment by carpii** [comment] 2024-05-23 10:36
ok, now merged into master

**Closed as completed by carpii** 2024-05-23 10:36 UTC
